fluttercandies/flutter_wechat_assets_picker

example/lib/pages/custom_picker_page.dart
example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
lib/src/constants/enums.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart

Hi,
I have added a new flag called showPreview to AssetPicker.pickAssets.
Default behavior (default value of showPreview parameter is true) is identical to the behavior so far: if you click an asset, you will get a preview of it. If you click the small circle, you select the asset.
But if you provide showPreview with false, there is no option to show preview. Instead, click on an assert will either add it to selection (multi assets mode) or select it (single assets more). 
That behavior is closer to "mainstream" application which have an image picker integrated (Facebook, Whatsapp, Instgram, Megatok, etc..).
I hope you will find this PR interesting and worthy to integrate soon.
Thank you,
Yaniv

✨ Ability to disable preview of assets using flag (showPreview)

---

example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart

Resolves #110 .
cc @yanivshaked

🐛 Fix Wechat Moment preview issue

---

lib/src/delegates/asset_picker_builder_delegate.dart

For SpecialPickerType.noPreview, the confirm button is missing.
Show confirm button for iOS on app bar.
Note that using de morgan's law doesn't make the code any nicer, I think this is the best alternative.

🐛 SpecialPickerType.noPreview: Confirm button is missing on iOS

---

lib/src/delegates/asset_picker_builder_delegate.dart

When changing folders, scroll controller is set to jump to 0 - but scroll controller was not used.

[Exception fix] Missing scroller controller

---

lib/src/widget/custom_checkbox.dart

Due to the fact that the flutter team has removed the RenderToggle class from the beta and master channel, this plugin is not working anymore on both of these channels. To make it work again, I simply copied the code for the rendertoggle class and all its sub classes.
Now the project is working again.
This can be a work around until the beta channel is merged with the stable channel

implementing render toggle class so this version will also work with the flutter beta and master channel

---

lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart

🐛 Fix keep offset jumping recovery issues

---

lib/src/delegates/asset_picker_builder_delegate.dart

@AlexV525 
This fixes the following issue on iOS. It is possible this is an overkill, and issue can be solved in a softer manner.

🐛 Fix refresh issue on switching folders

---

lib/src/provider/asset_entity_image_provider.dart
lib/src/widget/builder/image_page_builder.dart
lib/src/widget/builder/locally_available_builder.dart
lib/src/widget/builder/video_page_builder.dart
pubspec.yaml

Now that `photo_manager` supports checking whether the asset is locally available using the `Future` getter `AssetEntity.isLocallyAvailable`, so we can smoothly integrate the iCloud feature along with the `PMProgressHandler`.
This feature should be only involved with iOS and iCloud assets.
Related to #83 .

Integrate iCloud progress overview in previews

---

lib/src/delegates/asset_picker_builder_delegate.dart

With current display, file name is cut, most of the real estate is used by the audio track symbol:
Suggesting to use 3 lines for the filename, moving the audio track next to the duration:

🎨 Improve audio item layout

---

example/lib/constants/picker_method.dart
example/lib/customs/pickers/directory_file_asset_picker.dart
lib/src/constants/constants.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_text_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker.dart
lib/wechat_assets_picker.dart

Text delegates can be obtained according to `Locale`.
Breaking changes:
- `AssetsPickerTextDelegate` -> `AssetPickerTextDelegate`
- ~`AssetPickerTextDelegate.heicNotSupported`~
- `*TextDelegate` -> `*AssetPickerTextDelagate`

⚡ Improve text delegate

---

README-ZH.md
README.md
example/README.md
example/lib/constants/custom_pick_method.dart
example/lib/constants/page_mixin.dart
example/lib/constants/picker_method.dart
example/lib/customs/CONTRIBUTING.md
example/lib/customs/custom_picker_page.dart
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
example/lib/widgets/method_list_view.dart
example/lib/widgets/selected_assets_list_view.dart
example/pubspec.yaml
lib/src/constants/colors.dart
lib/src/constants/constants.dart
lib/src/constants/enums.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/internal/methods.dart
lib/src/internal/singleton.dart
lib/src/provider/asset_picker_provider.dart
lib/src/widget/asset_picker.dart
lib/src/widget/asset_picker_app_bar.dart
lib/src/widget/builder/asset_entity_grid_item_builder.dart
lib/src/widget/builder/audio_page_builder.dart
lib/src/widget/builder/video_page_builder.dart
lib/wechat_assets_picker.dart
pubspec.yaml

See #237.
Changes:
- Expose `defaultThemeColorWeChat`, `defaultAssetGridPreviewSize`.
- Expose `AssetPickerAppBar`.
- Split inner singleton and constants.
- Add `AssetPickerBuilderDelegate.initState`.
- Add `AssetPickerBuilderDelegate.onAssetsChanged`.
- Add `AssetPickerProvider.setPathThumbnail`.
- Use `meta` package explicitly.
Breaking changes:
- `provider` is removed from `AssetPicker.pickAssetsWithDelegate`.
- `AssetPickerProvider` is no longer exists at the ancestors of `AssetPickerBuilderDelegate`, delegates should provide their own providers manually.
- `keepScrollOffset` is moved from `AssetPickerBuilderDelegate` to `DefaultAssetPickerBuilderDelegate`.
- `isSingleAssetMode` is now an abstract field in `AssetPickerBuilderDelegate`.
- `build` is now an abstract method in …

♻️ Improve architecture for better customizations

---

README-ZH.md
README.md
lib/src/provider/asset_picker_provider.dart
lib/src/widget/asset_picker.dart
lib/src/widget/asset_picker_page_route.dart

Resolves #247.
Breaking changes:
- `routeCurve` and `routeDuration` are removed, instead with `pageRouteBuilder`.
- `DefaultAssetPickerProvider` no longer waits 300ms for initializations.

🚀 Extend page route

---

example/lib/constants/picker_method.dart
lib/src/constants/config.dart
lib/src/constants/typedefs.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker.dart
lib/src/widget/asset_picker_viewer.dart
lib/wechat_assets_picker.dart

Resolves #262.
- `specialItemBuilder` has a different signature.
- `allowSpecialItemWhenEmpty` has been removed.
Before:
```dart
specialItemBuilder: (BuildContext context) {
return someWidget;
}
```
After:
```dart
specialItemBuilder: (BuildContext context, AssetPathEntity? path, int length) {
if (path?.isAll != true) {
return null;
}
return someWidget;
}
```

🚀 Support predictable special item display

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
pubspec.yaml

`onChangingSelected` now returns a boolean to indicate whether the asset passed the `selectPredicate`.

⚡️ Improve `onChangingSelected` in `AssetPickerViewerBuilderDelegate`

---

CHANGELOG.md
analysis_options.yaml
example/lib/constants/picker_method.dart
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/pubspec.yaml
guides/migration_guide.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/sort_path_delegate.dart
lib/src/models/path_wrapper.dart
lib/src/provider/asset_picker_provider.dart
lib/wechat_assets_picker.dart
pubspec.yaml
test/delegates/builder_delegate_test.dart

`AssetPathEntity.assetCountAsync` was provided since https://github.com/fluttercandies/flutter_photo_manager/pull/784 of photo_manager.
By migrating the asynchronous getter, we need to introduce a wrapper `PathWrapper` to hold asset count and thumbnail data in the same place, but can be in different time spaces.
This PR brings breaking changes, as recorded:
- `AssetPickerProvider.currentPath` has been changed from `Path?` to `PathWrapper<Path>?`.
- `AssetPickerProvider.pathsList` has been removed, and added `AssetPickerProvider.paths`.
- `AssetPickerProvider.totalAssetsCount` is now nullable.
- `AssetPickerProvider.getThumbnailFromPath` and `AssetPickerProvider.switchPath` have different signature from `Path` to `PathWrapper<Path>`.
- `AssetPickerBuilderDelegate.pathEntityWidget` has …

✨ Introduce `PathWrapper`

---

CHANGELOG.md
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

- Improve `BuildContext` usages to obtain the correct directionality for the assets grid.
- Provide a better condition to the confirm button to make sure it displays correctly in all cases on iOS/macOS.
- Improve `bottomActionBar` in `DefaultAssetPickerBuilderDelegate`.

⚡️ Several improvements

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

I have updated the behavior where the asset picker for iOS would still show the confirm button in the bottom app bar even if `isSingleAssetMode == true` and `isPreviewEnabled == false`.
I assume this to be a bug as:
1. Android is behaving different (as expected)
2. Inside `appleOSLayout` I assume the `isAppleOS` check is unneeded
If suitable, please let me know whether this needs a changelog entry and which formatting requirements this has.
closes #377

Fix iOS button enabled for no preview

---

CHANGELOG.md
example/lib/customs/pickers/directory_file_asset_picker.dart
example/pubspec.yaml
guides/migration_guide.md
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

This PR expose grid `index` param in the `selectAsset` delegate function.

add: `index` param in `selectAsset`

---

CHANGELOG.md
example/lib/customs/custom_picker_page.dart
example/lib/customs/pickers/insta_asset_picker.dart
example/pubspec.yaml
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker_viewer.dart
pubspec.yaml

As we discussed previously #399.
Introduce `InstaAssetPickerBuilder` based on [insta_assets_picker](https://github.com/LeGoffMael/insta_assets_picker) which reproduces instagram layout.
- setup a complete different: layout, select and view logic
- use `keepScrollOffset` when set to true to restore scroll and preview
- customize `DefaultAssetPickerViewerBuilderDelegate` (currently there is no example for it)
Tested on both iOS and Android.
- Fixed an issue in `AssetPickerViewer`, when not used in a new pushed route, `initStateAndTicker` would be omitted.
<video src="https://user-images.githubusercontent.com/22376981/209911099-26c718b9-cc0b-495d-8b52-b3d5fff0ab46.mov"/>

New custom insta delegate

---

CHANGELOG.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart

🚸 Allow to confirm 0 assets if there are selected assets previously

---

lib/src/provider/asset_picker_provider.dart

🐛 Fix disposed provider throwing error when fetching assets

---

lib/src/delegates/asset_picker_text_delegate.dart
test/test_utils.dart

Hi
I want Korean support, but in the case of the existing Pull Request, the process has been stopped since then, so I will improve the sentence more naturally and request it again.
please review it.
Thank you.
https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/48482259/493115d5-f0cc-41c6-a5b9-b30514ed73ea

Add Korean localization

---

analysis_options.yaml
example/lib/customs/pickers/insta_asset_picker.dart
lib/src/delegates/asset_picker_builder_delegate.dart
test/test_utils.dart

analysis_options.yaml
```diff
- includes: package:flutter_lints/flutter.yaml
+ include: package:flutter_lints/flutter.yaml
```

🐛 Fix invalid linter

---

CHANGELOG.md
example/ios/Podfile
example/macos/Podfile
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

Resolves https://github.com/fluttercandies/flutter_wechat_assets_picker/discussions/507#discussioncomment-7572278.

⚡️ Use `viewAsset` in the preview button

---

CHANGELOG.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker_app_bar.dart
pubspec.yaml

- Fix unhandled child semantics with the app bar title.
- Fix styles around the app bar and other widgets.

🐛 Fix `AssetPickerAppBar`

---

CHANGELOG.md
example/android/app/src/main/AndroidManifest.xml
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/pubspec.yaml
guides/migration_guide.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_delegate.dart
lib/src/widget/asset_picker.dart
pubspec.yaml
test/test_utils.dart

- Support limited permission displays on Android. This also deprecates `iOSPermissionOverlay`.
- Requests with the correct options with the picker.
- Improves the limited overlay padding on Android.
- Adds permission request lock for the picker state.

🐛 Fixes permission requests

---

CHANGELOG.md
lib/src/provider/asset_picker_provider.dart
lib/src/widget/asset_picker.dart

1. Change the fetching steps to loading the first album first, then the others.
2. Use `AdvancedCustomFilter` by default to order items in desc without extra search queries to decrease the query complexity.
- Resolves #496
- Resolves #526
- Resolves #547

⚡️ Split assets fetching into separate steps

---

lib/src/delegates/asset_picker_text_delegate.dart
test/delegates_test.dart

🚀 Support matching script and country code of locales with the text delegate

---

lib/src/delegates/asset_picker_text_delegate.dart

This change adds Traditional Chinese localization and return it when the
locale is zh-Hant. We have to use the languageCode and scriptCode to
differentiate between Simplified and Traditional Chinese.
Summary of changes:
- Implement TraditionalChineseAssetPickerTextDelegate
- Add TraditionalChineseAssetPickerTextDelegate to the list of delegates.
- Sort the list of delegates alphabetically.
- Remove all toLowerCase() calls to make sure we can return the correct
delegate.
https://github.com/user-attachments/assets/c4d140d0-2020-4de7-9468-f6e7a2e02c98

Add Traditional Chinese localization

---

.github/workflows/runnable.yml
CHANGELOG.md
example/android/app/build.gradle
example/android/gradle.properties
example/android/gradle/wrapper/gradle-wrapper.properties
example/android/settings.gradle
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/Info.plist
example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/macos/Runner/AppDelegate.swift
example/pubspec.yaml
pubspec.yaml

📌 Allow `extended_image` v10

---

lib/src/widget/asset_picker_page_route.dart

在 AssetPickerPageRoute 构造函数中添加 super.settings 配置，以便于通过 NavigatorObserver 采集页面浏览时，能够正确拿到 RouteSettings

支持业务 App 页面浏览的埋点述求

---

CHANGELOG.md
lib/src/delegates/asset_picker_viewer_builder_delegate.dart

🐛 Fix `selectPredicate` not being called when selecting the video asset under the WeChat Moment mode
