fluttercandies/flutter_wechat_assets_picker

example/lib/pages/multi_assets_page.dart
lib/src/constants/custom_scroll_physics.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart

Further fix to #110 .
cc @yanivshaked

🐛 Further fix to the wrong behavior in WeChat Moment video preview

---

example/lib/pages/custom_picker_page.dart
lib/src/constants/enums.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker_viewer.dart

See related [Issue](https://github.com/fluttercandies/flutter_wechat_assets_picker/issues/115).

[Fix] Make sure no more than maxAssets are selected by the asset picker viewer

---

example/lib/main.dart
example/lib/pages/custom_picker_page.dart
example/lib/pages/home_page.dart
example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/fixed_appbar.dart

* `EdgeInsets` -> `EdgeInsetsDirectional`
* `Positioned` -> `PositionedDirectional`
* Some other RTL fit changes.
cc @yanivshaked Take a look.

✨ Support RTL

---

example/lib/constants/picker_method.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart
lib/src/widget/builder/asset_entity_grid_item_builder.dart
lib/src/widget/builder/asset_grid_item_builder.dart
lib/wechat_assets_picker.dart

Resolves #127 .
This is a minimum solution to solve the issue directly, without any breaking changes.

♻️ Split `AssetGridItemBuilder` to solve the rebuild issue

---

lib/src/delegates/assets_picker_text_delegate.dart

Russian localization for plugin.

Added Russian text delegate 

---

lib/src/delegates/assets_picker_text_delegate.dart

feat(assets_picker_text_delegate.dart): add Japanese text delegate

---

README-ZH.md
README.md

#61 
supplementary media location permission (ACCESS_MEDIA_LOCATION) document
由于上次pr的有问题，重新pr。

补充媒体位置权限(ACCESS_MEDIA_LOCATION)文档

---

lib/src/delegates/assets_picker_text_delegate.dart

Ref #161 , As the headline states :-)

[Text Delegate] Hebrew support for new fields

---

lib/src/delegates/assets_picker_text_delegate.dart

Added missing spaces and periods.

[Text Delegates] Minor punctuation fixes

---

example/lib/constants/picker_method.dart
example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
lib/src/constants/constants.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart

Introduce `keepScrollOffset` only when using the `pickAssetsWithDelegate` method.

✨ Add `keepScrollOffset` for the `AssetPickerBuilderDelegate`

---

example/lib/constants/picker_method.dart
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/main.dart
example/lib/pages/home_page.dart
example/lib/pages/splash_page.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/delegates/assets_picker_text_delegate.dart
lib/src/widget/builder/audio_page_builder.dart
lib/src/widget/builder/video_page_builder.dart
lib/src/widget/scale_text.dart

Resolves #217.
Thanks to @luomo-pro, who provides solid feedback with correctness and usability.
- Add `selectAsset`, `assetGridItemSemanticsBuilder` to `AssetPickerBuilderDelegate`.
- `AssetPickerBuilderDelegate.selectIndicator` signature changed.
- More field have been added to the `AssetsPickerTextDelegate`.

✨ Add full semantics support

---

example/lib/constants/picker_method.dart
example/lib/pages/multi_assets_page.dart
example/lib/pages/single_assets_page.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker.dart

✨ Implement the default light theme

---

lib/src/delegates/asset_picker_text_delegate.dart

ru translation for semantics fields

---

README-ZH.md
README.md
example/lib/constants/picker_method.dart
example/lib/pages/multi_assets_page.dart
lib/src/constants/config.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart
lib/src/widget/asset_picker_page_route.dart
lib/wechat_assets_picker.dart

Breaking changes:
- The default `requestType` is changed from `RequestType.image` to `RequestType.common`.

♻️ Abstract `AssetPickerConfig`

---

lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_text_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/builder/asset_entity_grid_item_builder.dart
lib/src/widget/builder/audio_page_builder.dart
lib/src/widget/builder/video_page_builder.dart

Related to #239, Hebrew fields need to be updated.

✨ Allow text delegates fallback to another one with semantics

---

lib/src/delegates/asset_picker_text_delegate.dart

[French] Text Delegate

---

lib/src/widget/builder/image_page_builder.dart
lib/src/widget/builder/locally_available_builder.dart
pubspec.yaml

Depend on https://github.com/fluttercandies/flutter_photo_manager/pull/719.
This also fixes some random preview issues.

🚑️ Fix `LocallyAvailableBuilder` with more edge conditions

---

lib/src/delegates/asset_picker_text_delegate.dart

text_delegate_ japanese_support

---

example/lib/customs/pickers/directory_file_asset_picker.dart
example/pubspec.yaml
lib/src/widget/builder/image_page_builder.dart
pubspec.yaml

⚡️ Support compile on the Web

---

README-ZH.md
README.md
lib/src/constants/config.dart
lib/src/constants/typedefs.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart

✨ `LimitedPermissionOverlayPredicate`

---

README-ZH.md
README.md
lib/src/constants/config.dart
lib/src/constants/typedefs.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/widget/asset_picker.dart

Allow users to customize the displayed path name rather than using the `SortDelegate`.

✨ `PathNameBuilder`

---

lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart

Resolves #309, also allow presenting limited when assets are empty.

🚸 Update how paths get update

---

lib/src/delegates/asset_picker_builder_delegate.dart

As a part of #313, some exceptions will throw when building with multiple cases.

⚡️ Improve `specialItemBuilder`

---

lib/src/delegates/asset_picker_delegate.dart
lib/src/widget/asset_picker.dart
lib/wechat_assets_picker.dart
test/delegates/builder_delegate_test.dart

♻️ Separate `AssetPickerDelegate`

---

CHANGELOG.md
example/lib/customs/pickers/directory_file_asset_picker.dart
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

Also upgrade to latest `photo_manager`.

🐛 Unify indicators usage

---

CHANGELOG.md
example/pubspec.yaml
lib/src/provider/asset_picker_provider.dart
pubspec.yaml

🐛 Fix not updated empty flag

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/sort_path_delegate.dart
pubspec.yaml
test/delegates/sort_path_delegate_test.dart

🐛 Fix invalid path sort

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml
test/config_test.dart
test/test_utils.dart
test/widget_test.dart

🐛 Fix conditions with the confirm button

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml
test/widget_test.dart

🐛 Fix the confirm button when selecting multiple assets with no preview

---

CHANGELOG.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart

🐛 Correct behaviors when the access is limited

---

CHANGELOG.md
lib/src/widget/asset_picker_app_bar.dart

Part of #398 is valid, this PR continues from it.

💄 Improve UI details in the `AssetPickerAppBar`

---

.all-contributorsrc
README-ZH.md
README.md
example/README.md
example/lib/constants/picker_method.dart
pubspec.yaml

- Better orders of each section.
- More specific features indication.
- Link more docs to PM.
- Remove redundant descriptions.
- Add descriptions about fields in `AssetPickerConfig`.
- Add pseudo codes for uploading `AssetEntity`.

📝 Improve docs

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart
pubspec.yaml

⚡️ Use completer to avoid duplicate load assets

---

README-ZH.md
README.md

Hi @AlexV525, i want add Vietnamese to READMEs, please help me review this PR. Thank you!

Add Vietnamese to READMEs

---

CHANGELOG.md
README-ZH.md
README.md
example/lib/main.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/builder/audio_page_builder.dart
lib/src/widget/builder/video_page_builder.dart
pubspec.yaml

💄 Roll UI design WeChat 8.3.x

---

CHANGELOG.md
example/lib/constants/extensions.dart
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/insta_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/lib/l10n/app_en.arb
example/lib/l10n/app_zh.arb
example/lib/l10n/gen/app_localizations.dart
example/lib/l10n/gen/app_localizations_en.dart
example/lib/l10n/gen/app_localizations_zh.dart
example/pubspec.yaml
lib/src/constants/extensions.dart
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/asset_picker_app_bar.dart
lib/src/widget/builder/audio_page_builder.dart
lib/src/widget/builder/locally_available_builder.dart
pubspec.yaml

⚡️ Add `appBarPreferredSize`

---

CHANGELOG.md
example/android/app/build.gradle
example/lib/customs/pickers/insta_asset_picker.dart
example/lib/customs/pickers/multi_tabs_assets_picker.dart
example/pubspec.yaml
guides/migration_guide.md
lib/src/constants/config.dart
lib/src/delegates/asset_picker_delegate.dart
lib/src/widget/asset_picker.dart
lib/src/widget/asset_picker_viewer.dart
pubspec.yaml
test/test_utils.dart

Justify permission details between requests.
Resolves #516.

✨ Integrate `PermissionRequestOption` for callers

---

CHANGELOG.md
example/lib/customs/pickers/directory_file_asset_picker.dart
example/lib/customs/pickers/insta_asset_picker.dart
guides/migration_guide.md
lib/src/delegates/asset_picker_builder_delegate.dart

🐛 Fix view assets with only selected

---

lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/provider/asset_picker_provider.dart

🔥 Make the first asset count not blocking loads

---

CHANGELOG.md
lib/src/delegates/asset_picker_delegate.dart
lib/src/widget/asset_picker.dart
test/test_utils.dart

🐛 Use `PermissionRequestOption` as much as possible

---

CHANGELOG.md
lib/src/provider/asset_picker_provider.dart

🥅 Raise more errors for non-synced paths

---

.github/workflows/publish.yml
.github/workflows/publishable.yml
.github/workflows/runnable.yml
CHANGELOG.md
example/l10n.yaml
example/lib/l10n/gen/app_localizations.dart
example/lib/l10n/gen/app_localizations_en.dart
example/lib/l10n/gen/app_localizations_zh.dart
lib/src/delegates/asset_picker_text_delegate.dart
pubspec.yaml

Provides checks for dart code analysis.

CI: Action - Code Analysis

---

CHANGELOG.md
lib/src/delegates/asset_picker_viewer_builder_delegate.dart

🐛 Fix current asset in the picker viewer

---

CHANGELOG.md
example/pubspec.yaml
lib/src/delegates/asset_picker_builder_delegate.dart
pubspec.yaml

🐛 Fix index reverting in `viewAsset`

---

CHANGELOG.md
lib/src/delegates/asset_picker_viewer_builder_delegate.dart

🐛 Fix the app bar of the viewer that is not animating.

---

CHANGELOG.md
analysis_options.yaml
lib/src/provider/asset_picker_provider.dart

🐛 Reset the has more to load flag between path switching

---

CHANGELOG.md
lib/src/delegates/asset_picker_builder_delegate.dart

Resolves https://github.com/fluttercandies/flutter_photo_manager/issues/1215

🐛 Allows assets changing when no path previously

---

CHANGELOG.md
example/lib/l10n/gen/app_localizations.dart
example/lib/l10n/gen/app_localizations_en.dart
example/lib/l10n/gen/app_localizations_zh.dart
example/pubspec.yaml
pubspec.yaml

⬆️ Allows `extended_image: ^9.0.0`

---

CHANGELOG.md
lib/src/delegates/asset_picker_builder_delegate.dart
lib/src/delegates/asset_picker_viewer_builder_delegate.dart
lib/src/widget/builder/audio_page_builder.dart

Update according to the feedback from @luomo-pro

♿️ Fix semantics issues
